orgAllowlist: "github.com/smutosey/*"
github:
  user: smutosey
  token: token
  secret: secret

service:
  type: NodePort
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  labels: {}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  host: atlantis.smutosey.ru

atlantisDataDirectory: /atlantis-data

volumeClaim:
  enabled: true
  # -- Disk space available to check out repositories.
  dataStorage: 2Gi
  # -- Storage class name (if possible, use a resizable one).
  storageClassName: "local-path"
  accessModes: ["ReadWriteOnce"]

repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: []
    workflow: default
    pre_workflow_hooks:
      - run: cp .terraformrc ~/.terraformrc
        description: Generating configs
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
  metrics:
    prometheus:
      endpoint: /metrics