alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - alertmanager.smutosey.ru
    pathType: Prefix

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - grafana.smutosey.ru
    pathType: Prefix

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - prometheus.smutosey.ru
    pathType: Prefix